gateway:
  sandbox:
  uat: d



spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/oldface?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:cashc0wA}
    druid:
      keep-alive: true
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      log-abandoned: true